# 设置项
settings:
  # Dodo消息转发相关
  SendDodoMessage:
    # 是否启用
    Enable: true
    # 消息格式（%message%代表消息内容，%sender%代表发送者的群昵称，可使用颜色代码）
    format: "§f[§eDodo消息§f]§b%sender%：§f%message%"
    # 监听的频道ID
    channelId: "aa"
  # 服内消息转发相关
  SendServerMessage:
    # 是否启用
    Enable: true
    # 消息格式（%message%代表消息内容，%sender%代表发送者的显示名）
    format: "[服内消息]%sender%：%message%"
    # 发送的频道ID
    channelId: "aa"
  # 切换服务器相关的事件
  ChanceServer:
    # 是否启用
    Enable: true
    # 切换到哪些服务器，如果为“all”，那么就是进入切换所有服务器都会提醒（包括进入到登录服务器）
    servers:
      - server1
      - server2
    # 消息格式（%server%代表服务器，%player%代表玩家的显示名）
    format: "%member%加入了%server%子服务器"
    # 发送的频道ID
    channelId: "aa"
  # 进服消息提醒（发送到Dodo频道）
  JoinMessage:
    # 是否启用
    Enable: true
    # 消息格式（%message%代表消息内容，%player%代表玩家的显示名）
    format: "%player%进入了服务器"
    # 发送的频道ID
    channelId: "aa"
  # 退服消息提醒（发送到Dodo频道）
  LeaveMessage:
    # 是否启用
    Enable: true
    # 消息格式（%message%代表消息内容，%player%代表玩家的显示名）
    format: "%player%退出了服务器"
    # 发送的频道ID
    channelId: "aa"
  # 机器人机器人鉴权Token
  botToken: "token"
  # 机器人唯一标识
  botClientId: "clientId"
